server:
  port: 8083
  address: 0.0.0.0

spring:
  application:
    name: account-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:

    # ─── PRIMARY ────────────────────────────────────────────────
    primary:
      jdbc-url: jdbc:mysql://citicore-mysql-primary.cnk8ckkm2hsk.ap-south-1.rds.amazonaws.com:3306/citicore_account?sslMode=VERIFY_IDENTITY&serverTimezone=UTC&trustCertificateKeyStoreUrl=file:/app/rds/rds-truststore.jks&trustCertificateKeyStorePassword=${RDS_TRUSTSTORE_PASSWORD}
      username: ${DB_PRIMARY_USERNAME}
      password: ${DB_PRIMARY_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    # ─── REPLICA ───────────────────────────────────────────────
    replica:
      jdbc-url: jdbc:mysql://citicore-mysql-replica.cnk8ckkm2hsk.ap-south-1.rds.amazonaws.com:3306/citicore_account?sslMode=VERIFY_IDENTITY&serverTimezone=UTC&trustCertificateKeyStoreUrl=file:/app/rds/rds-truststore.jks&trustCertificateKeyStorePassword=${RDS_TRUSTSTORE_PASSWORD}
      username: ${DB_REPLICA_USERNAME}
      password: ${DB_REPLICA_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  # ─── JPA ────────────────────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # ─── Schema init — runs schema.sql on startup ─────────────────
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  # ─── Redis ──────────────────────────────────────────────────
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  task:
    scheduling:
      pool:
        size: 2

citicore:
  account:
    min-savings-balance: 1000
    min-current-balance: 5000

logging:
  level:
    com.citicore.account: DEBUG
    org.springframework.data.redis: WARN
    org.apache.kafka: WARN
