# ─────────────────────────────────────────────────────────────
# transaction-service.yml — OVERRIDES ONLY
# Everything not listed here is inherited from application.yml
# ─────────────────────────────────────────────────────────────

server:
  port: 8084

spring:
  application:
    name: transaction-service

  # ─── Database (DEV: H2) ───────────────────────────────────
  # ─── Database (DEV: H2) ───────────────────────────────────
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  # ─── Kafka consumer group override ────────────────────────
  # Consumes: credit-success-topic, credit-failed-topic,
  #           debit-failed-topic, reversal-success-topic
  kafka:
    consumer:
      group-id: transaction-group

  # ─── Feign (account-service pre-validation) ───────────────
  cloud:
    openfeign:
      client:
        config:
          account-service:
            connect-timeout: 3000
            read-timeout: 5000

  # ─── Scheduling (OutboxPublisher polls every 5s) ──────────
  task:
    scheduling:
      pool:
        size: 2

# ─── Transaction business rules ───────────────────────────────
citicore:
  transaction:
    daily-limit:
      TRANSFER: 500000
      DEPOSIT: 1000000
      WITHDRAWAL: 200000

logging:
  level:
    com.citicore.transaction: DEBUG

# ─── PROD override ────────────────────────────────────────────
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/citicore_txn
#     driver-class-name: org.postgresql.Driver
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: validate
#     show-sql: false