server:
  port: 8084

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring:
  datasource:
    url: jdbc:h2:mem:transdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


aws:
  region: ap-south-1
  s3:
    bucket: your-kyc-bucket
